./guest_inference_tsdp \
	120 \
	models/mobilenetv1_tsdp/mobilenetv1_1_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_1_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_1_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_1_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_1_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_2_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_2_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_2_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_2_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_2_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_3_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_3_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_3_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_3_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_3_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_4_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_4_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_4_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_4_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_4_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_5_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_5_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_5_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_5_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_5_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_6_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_6_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_6_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_6_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_6_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_7_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_7_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_7_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_7_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_7_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_8_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_8_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_8_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_8_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_8_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_9_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_9_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_9_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_9_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_9_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_10_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_10_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_10_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_10_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_10_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_11_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_11_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_11_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_11_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_11_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_12_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_12_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_12_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_12_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_12_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_13_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_13_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_13_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_13_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_13_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_14_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_14_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_14_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_14_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_14_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_15_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_15_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_15_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_15_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_15_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_16_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_16_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_16_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_16_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_16_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_17_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_17_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_17_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_17_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_17_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_18_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_18_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_18_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_18_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_18_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_19_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_19_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_19_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_19_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_19_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_20_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_20_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_20_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_20_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_20_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_21_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_21_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_21_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_21_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_21_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_22_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_22_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_22_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_22_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_22_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_23_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_23_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_23_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_23_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_23_5.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_24_1.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_24_2.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_24_3.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_24_4.tflite \
	models/mobilenetv1_tsdp/mobilenetv1_24_5.tflite
